simplify

diff --git a/.github/workflows/build-check.yml b/.github/workflows/build-check.yml
--- a/.github/workflows/build-check.yml
+++ b/.github/workflows/build-check.yml
@@ -3,10 +3,12 @@ on: [push]
 jobs:
   run-build:
     runs-on: ubuntu-latest
-    container:
-        image: ghcr.io/northeastern-electric-racing/embedded-base:main
     timeout-minutes: 10
     steps:
       - uses: actions/checkout@v4
       - name: Execute Make
-        run: docker compose run --rm ner-gcc-arm make -j `nproc`
+        run: |
+            if ! docker compose run --rm ner-gcc-arm make -j `nproc`; then
+            echo "The application has failed to build."
+            exit 1  # This will cause the workflow to fail
+            fi
